[package]
name = "telegram-notifyrs"
version = "0.1.0"
authors = ["Evan Chaney <evanachaney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.10.8"
url = "2.1.0"
serde_json = "1.0.41"